/** @jsx React.DOM */

module.exports = {
	LOAD_ALARMS: "LOAD_ALARMS",
	ADD_MENU_ITEM: "ADD_MENU_ITEM",
	LOAD_MENU_ITEMS: "LOAD_MENU_ITEMS",
	GOTTEN_ALARM_DETAILS: "GOTTEN_ALARM_DETAILS",
	GOTTEN_ALARMS_GRAPHS: "GOTTEN_ALARMS_GRAPHS",
	GOTTEN_ALARMS_COUNT: "GOTTEN_ALARMS_COUNT"
};
